### ISSUE TITLE
overview of progresses

### ISSUE THREAD

**Issue by jcolomb** [CenterForOpenScience/osfr#39]
Hi Chris,

It would be good to have a document stating the progresses, what is possible to do with the package already (with some examples maybe) and what are your next steps. Is COS involved in this project?  

I am looking for a way to get a readable and writable, online (via R) accessible spreadsheet and do not want to use googledoc, and Rfigshare is down since figshare changed their API (see https://github.com/jcolomb/HCS_analysis/issues/10 , a project I plan to move to shiny at some point, but that will be over in march at the latest)... 
I will look into this package next week and try it out, but it would be good to have an idea of when version 1.0.0 (stable) will be available. 
Thanks,
Julien

**Comment by chartgerink** [comment]
Thanks @jcolomb for your interest! It is a bit difficult for me to provide a timeline because this project keeps on running into either time, motivation, or programmatic problems/difficulties. I am trying to have the basic functionality down by the end of the year. What kind of functionality are you specifically looking for?

COS is not directly involved in this project, but are aware of it and are supportive of the idea (plus I get support when there's troubles with the API).

**Comment by csoderberg** [comment]
Closing this issue out, as we're about to pull in a completely revamped version fo the package and the mvp branch as been merged into master as is in preparation for the new stable code.
