### ISSUE TITLE
path_file not working 

### ISSUE THREAD

**Issue by jcolomb** [CenterForOpenScience/osfr#68]
example not working:

read.csv(osfr::path_file("5z2bh"))
#> Error in get_config(private): Not logged in.

**Comment by jcolomb** [comment]
the function works if one is logged in.

I suggest using
path_file (x) = paste0("http://www.osf.io/download/",x) for public file.

but one should probably see why get_config is not working correctly ?

**Comment by bgrich** [comment]
Hi @jcolomb! The error coming from `get_config()` is due to changes in the way being logged in is handled. `osfr` now requires the user to be logged in using a personal access token to use most of the functions in the package. One exception to this is `download_files()`, which automatically checks if the file is public and allows a download.

I'll update `path_file()` with the changes made to `download_files()` that allow for automatic handling of public/private status. In this case, the `private` argument in `path_file()` will be removed and `path_file()` will first attempt to access the download link assuming it is a private file. If that does not work, it will use the users login information and assume it is a private file. This will also add in the ability to get a download link for files that have view-only links.

Thanks for letting me know about the error!

**Comment by bgrich** [comment]
This should be fixed in PR #69. Let me know if there are any more problems with it!
