### ISSUE TITLE
Error in path[[i]] : subscript out of bounds when cloning project

### ISSUE THREAD

**Issue by kohlkopf** [CenterForOpenScience/osfr#75]
Receiving error `Error in path[[i]] : subscript out of bounds` when attempting to download project `ycu8j` using `clone_project`. Also receiving `Error in gregexpr("/", txt)[[1]] : subscript out of bounds` when using `download_files()`. 

I should note that I am trying to download data to an RStudio Cloud instance and believe the issue is probably on that side of things.

**Comment by csoderberg** [comment]
@kohlkopf Thanks for reporting this. I'm getting the first error when attempting to clone the project to my local machine, so I think it's unrelated to the cloud instances (it looks like it may be related to the fact that that project has folder in it). 

For the 2nd issue, could you provide a bit more information about the call you were making with download files that produced the error?

**Comment by kohlkopf** [comment]
I call `download_files(id = "ycu8j")`, the ID being XXXX of osf.io/XXXX.

**Comment by FredHasselman** [comment]
Hi @csoderberg et al.

I am responding to the download_files() issue raised by @kohlkopf, it was also mentioned in earlier issues, but is not completely resolved yet.

Here's what happens:

Suppose I want to call `download_files()` to download an OSF hosted dataset `TEST.csv` to a path generated by one of R's internal functions, e.g.
`path <- getwd()`

Then, in the `download_files()` function, line 17, the filename is generated as follows:
 `file <- paste0(path, res$data$attributes$name)`

The resulting value for `file` is: `/Users/FredTEST.csv`
This is because all paths returned by R's internal functions will not have a trailing separator.

A simple change that fixes this problem (and greatly enhances cross-platform stability) is:
`file <- file.path(path, res$data$attributes$name)`

The resulting value for `file` will be: `/Users/Fred/TEST.csv` and that's what I intended it to be!

I recommend to always use `file.path()` to construct filenames, it will automatically choose the separator that is native to the OS.

**Comment by csoderberg** [comment]
@FredHasselman thanks for the catch! Do you want to put this in as a pull request to the mvp branch so you can get commit credit?

**Comment by FredHasselman** [comment]
Ok!


On 28 November 2018 at 19:47:16, csoderberg (notifications@github.com)
wrote:

@FredHasselman <https://github.com/FredHasselman> thanks for the catch! Do
you want to put this in as a pull request to the mvp branch so you can get
commit credit?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CenterForOpenScience/osfr/issues/75#issuecomment-442560157>,
or mute the thread

**Comment by csoderberg** [comment]
This is relevant to the 0.1.1 release. The code has changed in the current version (0.2.0) and currently doesn't have clone_project functionality, so this is not relevant. If you're still interested in clone_project type functionality, we'd be happy to have a feature request related to it.
